### ISSUE TITLE
Expected object of type torch.cuda.LongTensor but found type torch.FloatTensor for argument #2 'other'

### ISSUE THREAD

**Issue by sathish331977** [bentrevett/pytorch-pos-tagging#2]
Ran into the following issue, while executing epochs
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-83bf30366feb> in <module>
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, train_iterator, optimizer, criterion, TAG_PAD_IDX)
     10     valid_loss, valid_acc = evaluate(model, valid_iterator, criterion, TAG_PAD_IDX)
     11 

<ipython-input-29-1cec3555a62e> in train(model, iterator, optimizer, criterion, tag_pad_idx)
     28         loss = criterion(predictions, tags)
     29 
---> 30         acc = categorical_accuracy(predictions, tags, tag_pad_idx)
     31 
     32         loss.backward()

<ipython-input-28-9c379edbc2e5> in categorical_accuracy(preds, y, tag_pad_idx)
      6     non_pad_elements = (y != tag_pad_idx).nonzero()
      7     correct = max_preds[non_pad_elements].squeeze(1).eq(y[non_pad_elements])
----> 8     return correct.sum() / torch.FloatTensor([y[non_pad_elements].shape[0]])

RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.FloatTensor for argument #2 'other'

**Comment by bentrevett** [comment]
Which notebook gives you this issue?

I'm unable to replicate on my end.

**Comment by sathish331977** [comment]
i used "1 - Simple RNN PoS Tagger.ipynb"

**Comment by bentrevett** [comment]
I'm still not able to replicate this error. 

What version of PyTorch and TorchText are you using? I'm using 1.3 and 0.4.

**Comment by sathish331977** [comment]
after upgrading pytorch version issue got resolved. Thank you for your patience with this issue.
